bh/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^skill/list/$',
        login_required(views.SkillList.as_view()), name='skills'),
    url(r'^skill/(?P<pk>[0-9]+)/$',
        login_required(views.skill), name='skill'),
    url(r'^action/list/$',
        login_required(views.ActionList.as_view()), name='actions'),
    url(r'^action/types/$',
        login_required(views.ActionCategoryList.as_view()), name='action_types'),
    url(r'^action/type/(?P<pk>[0-9]+)/$',
        login_required(views.action_type), name='action_type'),
    url(r'^action/(?P<pk>[0-9]+)/$',
        login_required(views.action), name='action'),
    url(r'^event/types/$',
        login_required(views.EventCategoryList.as_view()), name='event_types'),
    url(r'^event/type/(?P<pk>[0-9]+)/$',
        login_required(views.event_type), name='event_type'),
    url(r'^event/(?P<pk>[0-9]+)/$',
        login_required(views.event), name='event'),
    url(r'^address/list/$',
        login_required(views.AddressList.as_view()), name='addresses'),
    url(r'^address/(?P<pk>[0-9]+)/$',
        login_required(views.address), name='address'),
    url(r'^person/list/$',
        login_required(views.people_list), name='people'),
    url(r'^person/birthdays/list/$',
        login_required(views.people_birthdays_list), name='birthdays'),
    url(r'^person/(?P<pk>[0-9]+)/$',
        login_required(views.person), name='person'),
    url(r'^search/$',
        login_required(views.search), name='search'),
]

brotherhood/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views import static


urlpatterns = [
    url(r'', include(('bh.urls', 'bh'), namespace='bh')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns.append(
        url(
            r'^media/(?P<path>.*)$',
            static.serve,
            {'document_root': settings.MEDIA_ROOT}
        )
    )

bh/models.py
import os
import time
from hashlib import md5

from django.db import models
from django_resized import ResizedImageField
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe


DOW_CHOICES = (
    (0, 'Воскресенье'), (1, 'Понедельник'), (2, 'Вторник'),
    (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')
)


def hash_name(base):
    """
    :type base: str
    :rtype: str
    """
    return md5(base.encode('utf-8')).hexdigest()


def user_directory_path(instance, filename):
    """
    Returns url like /media/avatars/ad688b26ba3876751699c540e0e23ede.jpeg
    :type instance: Person
    :type filename: str
    :rtype: str
    """
    ext = filename.split('.')[-1].lower()
    path = 'avatars/{}.{}'.format(hash_name(str(instance)), ext)
    os_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.isfile(os_path):
        os.remove(os_path)
    return path


def photo_path(instance, filename):
    ext = filename.split('.')[-1].lower()
    dir_path = 'gallery_{}'.format(instance.gallery.pk)
    os_dir_path = os.path.join(settings.MEDIA_ROOT, dir_path)
    if os.path.exists(os_dir_path) and not os.path.isdir(os_dir_path):
        os.remove(os_dir_path)
    if not os.path.isdir(os_dir_path):
        os.mkdir(os_dir_path, 0o777)

    file_path = os.path.join(
        dir_path, '{}.{}'.format(hash_name(str(time.time())), ext)
    )
    os_path = os.path.join(settings.MEDIA_ROOT, file_path)
    if os.path.isfile(os_path):
        os.remove(os_path)
    return file_path


class Gallery(models.Model):
    name = models.CharField(
        null=False, blank=False, max_length=256,
        verbose_name='Название'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Галерея'
        verbose_name_plural = 'Галереи'


class Photo(models.Model):
    name = models.CharField(
        null=False, blank=False, max_length=256,
        verbose_name='Название'
    )
    image = ResizedImageField(
        upload_to=photo_path, null=False, blank=False,
        verbose_name='Фото', size=(1200, 1200),
    )
    gallery = models.ForeignKey(
        Gallery, on_delete=models.CASCADE, null=False, blank=False,
        verbose_name='Галерея', related_name='photos'
    )

    def image_tag(self):
        return mark_safe('<img src="{}" width=100 height=100 />'.format(self.image.url))
    image_tag.short_description = 'Изображение'

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'


class Address(models.Model):
    """
    Физический адрес проживания
    """

    name = models.CharField(
        null=False, blank=False, max_length=256,
        verbose_name='Название'
    )
    description = models.CharField(
        null=True, blank=True, max_length=256,
        verbose_name='Описание'
    )
    text = models.CharField(
        null=True, blank=True, max_length=256,
        verbose_name='Адрес'
    )
    # Точка на карте
    lng = models.FloatField(
        null=True, blank=True,
        verbose_name='Долгота'
    )
    lat = models.FloatField(
        null=True, blank=True,
        verbose_name='Широта'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Адрес'
        verbose_name_plural = 'Адреса'
        ordering = ['name']


class SignedDocument(models.Model):
    name = models.CharField(
        null=False, blank=False, max_length=256,
        verbose_name='Наименование'
    )
    description = models.TextField(
        null=True, blank=True,
        verbose_name='Описание'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подписанный документ'
        verbose_name_plural = 'Подписанные документы'


class Gender(object):
    male = 'm'
    female = 'f'


class Person(models.Model):
    first_name = models.CharField(
        null=False, blank=False, max_length=256,
        verbose_name='Имя'
    )
    middle_name = models.CharField(
        null=True, blank=True, max_length=256,
        verbose_name='Отчество'
    )
    last_name = models.CharField(
        null=False, blank=False, max_length=256,
        verbose_name='Фамилия'
    )
    maiden_name = models.CharField(
        null=True, blank=True, max_length=256,
        verbose_name='Девичья фамилия'
    )
    gender = models.CharField(
        choices=((Gender.male, 'Мужской'), (Gender.female, 'Женский')),
        default=Gender.male, null=False, blank=False, max_length=256,
        verbose_name='Пол'
    )
    created_at = models.DateTimeField(
        auto_now_add=True, null=False, editable=False
    )
    birthday = models.DateField(
        null=True, blank=True,
        verbose_name='День рождения'
    )
    occupation = models.CharField(
        null=True, blank=True, max_length=255,
        verbose_name='Род занятий'
    )
    specialty = models.CharField(
        null=True, blank=True, max_length=255,
        verbose_name='Образование, специальность'
    )
    description = models.TextField(
        null=True, blank=True,
        verbose_name='Примечания'
    )
    baptized = models.BooleanField(
        null=False, blank=False, default=False,
        verbose_name='Крещен'
    )
    baptized_at = models.DateField(
        null=True, blank=True,
        verbose_name='Дата крещения'
    )
    married = models.BooleanField(
        null=False, blank=False, default=False,
        verbose_name='Женат/Замужем'
    )
    married_at = models.DateField(
        null=True, blank=True,
        verbose_name='Дата бракосочетания'
    )
    address = models.ForeignKey(
        'Address', on_delete=models.SET_NULL, null=True, blank=True,
        verbose_name='Адрес', related_name='people'
    )
    image = ResizedImageField(
        upload_to=user_directory_path, null=True, blank=True, default=None,
        verbose_name='Фото', size=(500, 500)
    )
    skills = models.ManyToManyField(
        'Skill',  blank=True,  related_name='people',
        verbose_name='Дары и таланты',
    )
    signed_documents = models.ManyToManyField(
        'SignedDocument', blank=True, related_name='people',
        verbose_name='Подписанные документы',
    )
    member = models.BooleanField(
        null=False, blank=False, default=False,
        verbose_name='Член церкви'
    )
    gone_to_eternity = models.BooleanField(
        null=False, blank=False, default=False,
        verbose_name='Отошел в вечность'
    )
    gone = models.BooleanField(
        null=False, blank=False, default=False,
        verbose_name='Ушел из церкви'
    )
    gone_to_another_church = models.BooleanField(
        null=False, blank=False, default=False,
        verbose_name='Перешел в другую церковь'
    )
    staff = models.ForeignKey(
        'Staff', on_delete=models.SET_NULL, null=True, blank=True,
        verbose_name='Должность в церкви', related_name='people'
    )

    def clean(self):
        if self.baptized_at and not self.baptized:
            self.baptized = True

    def __str__(self):
        full_name = '{} {}'.format(
            self.last_name, self.first_name
        )
        if self.middle_name:
            full_name = '{} {}'.format(full_name, self.middle_name)
        return full_name

    class Meta:
        ordering = ['last_name', 'first_name']
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class Email(models.Model):
    """
    Адрес электронной почты.
    У одного человека может быть много адресов.
    """
    address = models.CharField(
        null=False, blank=False, unique=True, max_length=255,
        verbose_name='Адрес'
    )
    person = models.ForeignKey(
        'Person', on_delete=models.CASCADE, related_name='email'
    )

    def __str__(self):
        return self.address

    class Meta:
        verbose_name = 'E-mail'
        verbose_name_plural = 'E-mail'


class Social(models.Model):
    """
    Персональные страницы в социальных сетях.
    У одного человека может быть много аккаунтов.
    """
    SOCIAL = (
        ('vk', 'ВКонтакте'),
        ('fb', 'Facebook'),
        ('ln', 'LinkedIn'),
        ('tw', 'Twitter'),
        ('od', 'Одноклассники'),
        ('sk', 'Skype'),
    )
    name = models.CharField(
        null=False, choices=SOCIAL, max_length=2,
        verbose_name='Сеть'
    )
    link = models.CharField(
        null=False, blank=False, unique=True, max_length=255,
        verbose_name='Ссылка'
    )
    person = models.ForeignKey(
        'Person', on_delete=models.CASCADE, related_name='social'
    )

    def __str__(self):
        return self.link


class Phone(models.Model):
    """
    Телефонные номера
    """
    number = models.CharField(
        null=False, blank=False, max_length=255,
        verbose_name='Номер'
    )
    type = models.CharField(
        null=True, max_length=255, choices=(
            ('cell', 'Мобильный'), ('home', 'Домашний'),
            ('work', 'Рабочий'), ('other', 'Другое')
        ),
        verbose_name='Тип'
    )
    person = models.ForeignKey(
        'Person', blank=True, null=True, related_name='phone',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.number

    class Meta:
        verbose_name = 'Номер телефона'
        verbose_name_plural = 'Номера телефонов'


class Rel(object):
    husband = 'husband'
    wife = 'wife'
    son = 'son'
    daughter = 'daughter'
    father = 'father'
    mother = 'mother'
    brother = 'brother'
    sister = 'sister'
    grandfather = 'grandfather'
    grandmother = 'grandmother'
    grandson = 'grandson'
    granddaughter = 'granddaughter'
    great_grandfather = 'great_grandfather'
    great_grandmother = 'great_grandmother'
    great_grandson = 'great_grandson'
    great_granddaughter = 'great_granddaughter'
    father_in_low_m = 'father_in_low_m'
    father_in_low_f = 'father_in_low_f'

bh/forms.py
from django import forms

from .models import (
    EventType,
    Staff,
    Role,
    Skill,
    SignedDocument,
)


class SimpleSearch(forms.Form):
    gone_to_eternity = forms.BooleanField(
        label='Отображать отошедших в вечность',
        required=False,
    )
    gone_to_another_church = forms.BooleanField(
        label='Отображать перешедших в другую церковь',
        required=False,
    )
    gone = forms.BooleanField(
        label='Отображать ушедших из церкви',
        required=False,
    )


class ExtendedSearch(forms.Form):

    full_name = forms.CharField(
        label='Фамилия, имя, отчество',
        widget=forms.TextInput(attrs={'placeholder': 'Фамилия, имя, отчество'}),
        required=False,
    )
    baptized = forms.ChoiceField(
        choices=((2, 'Не важно'), (1, 'Да'), (0, 'Нет')),
        label='Крещен'
    )
    member = forms.ChoiceField(
        choices=((2, 'Не важно'), (1, 'Да'), (0, 'Нет')),
        label='Член церкви'
    )
    staff = forms.ChoiceField(choices=[], label='Должность в церкви')

    role = forms.ChoiceField(choices=[], label='Служение/роль в активностях')

    gender = forms.ChoiceField(
        choices=(('o', 'Не важно'), ('m', 'Мужской'), ('f', 'Женский')),
        label='Пол'
    )
    married = forms.ChoiceField(
        choices=((2, 'Не важно'), (0, 'Не в браке'), (1, 'В браке')),
        label='Женат/замужем'
    )
    age_older_than_choices = [(n, n) for n in range(100)]
    age_older_than_choices.insert(0, (-1, 'Не важно'))
    age_older_than = forms.ChoiceField(
        choices=age_older_than_choices,
        label='Возраст, от'
    )
    age_younger_than_choices = [(n, n) for n in range(1, 100)]
    age_younger_than_choices.append((-1, 'Не важно'))
    age_younger_than = forms.ChoiceField(
        choices=age_younger_than_choices,
        label='Возраст, до'
    )

    in_small_group = forms.ChoiceField(
        choices=((2, 'Не важно'), (0, 'Посещает'), (1, 'Не посещает')),
        label='Посещение малой группы'
    )
    gone_to_eternity = forms.BooleanField(
        label='Отображать отошедших в вечность',
        required=False,
    )
    gone_to_another_church = forms.BooleanField(
        label='Отображать перешедших в другую церковь',
        required=False,
    )
    gone = forms.BooleanField(
        label='Отображать ушедших из церкви',
        required=False,
    )

    event_presents = forms.ModelMultipleChoiceField(
        queryset=EventType.objects.all(),
        label='Посетил(а) события (все выбранные)',
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    event_absents = forms.ModelMultipleChoiceField(
        queryset=EventType.objects.all(),
        label='Не принимал(а) участия в событиях (ни в одном из выбранных)',
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    skills = forms.ModelMultipleChoiceField(
        queryset=Skill.objects.all(),
        label='Дары и таланты (любой из выбранных)',
        widget=forms.SelectMultiple,
        required=False
    )

    signed_documents = forms.ModelMultipleChoiceField(
        queryset=SignedDocument.objects.all(),
        label='Подписанные документы (любой из выбранных)',
        widget=forms.SelectMultiple,
        required=False
    )

    sort = forms.ChoiceField(
        choices=((0, 'Не важно'), (1, 'Возраст'),),
        label='Сортировка'
    )

    def __init__(self, *args, **kwargs):
        super(ExtendedSearch, self).__init__(*args, **kwargs)
        self.fields['staff'].choices = Staff.make_choices()
        self.fields['role'].choices = Role.make_choices()
        self.fields['age_older_than'].initial = -1
        self.fields['age_younger_than'].initial = -1

bh/templates/bh/action.html
{% extends "bh/main.html" %}

{% block actions %}active{% endblock %}

{% block content %}
    <h3>
        {{ action.name }} {% if action.action_type %}({{ action.action_type.name }}){% endif %}
        {% if user.is_superuser %}
            <a href="{% url 'admin:bh_action_change' action.pk %}">Edit</a>
        {% endif %}
    </h3>

    {% if action.description %}
        <p>
            <i>{{ action.description }}</i>
        </p>
    {% endif %}

	<div class="list-group">
		{% for role in action.roles.all %}
			<a class="list-group-item" href="{% url 'bh:person' pk=role.person.pk %}">
                {{ role.person }}
                {% if role.charge %}
                    ({{ role.charge }})
                {% elif role.role %}
                    ({{ role.role }})
                {% endif %}
            </a>
		{% endfor %}
	</div>

    {% if action.periods.count %}
        <div>
            <h4>Время проведения:</h4>
            <ul>
                {% for period in action.periods.all %}
                    <li>{{ period }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    {% if action.address %}<h4>Место: {{ action.address.name }}</h4>{% endif %}

    {% if action.address and action.address.lat and action.address.lng %}
        <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
        <div id="map" style="width: 600px; height: 400px; border:1px solid #ccc; padding:5px;"></div>
        <script type="text/javascript">
            ymaps.ready(init);
            var myMap;
            function init(){
                myMap = new ymaps.Map("map", {
                    center: [{{ action.address.lat|safe }}, {{ action.address.lng|safe }}],
                    zoom: 12
                });
                myPlacemark = new ymaps.Placemark(
                    [{{ action.address.lat|safe }}, {{ action.address.lng|safe }}],
                    {
                        balloonContentHeader: "{{ action.address.name }}",
                        balloonContentBody: "{{ action.address.description }}"
                    }
                );
                myMap.geoObjects.add(myPlacemark);
                myPlacemark.balloon.open();
            }
        </script>
    {% endif %}

{% endblock %}

bh/templates/bh/action_list.html
{% extends "bh/main.html" %}

{% block actions %}active{% endblock %}

{% block content %}

    <h3>Активности категории "{{ title }}"</h3>
	<div class="list-group">
		{% for action in actions.all %}
			<a class="list-group-item" href="{% url 'bh:action' pk=action.pk %}">{{ action }}</a>
		{% endfor %}
	</div>
{% endblock %}

bh/templates/bh/actiontype_list.html
{% extends "bh/main.html" %}

{% block actions %}active{% endblock %}

{% block content %}
    <h3>Категории активностей</h3>
    <div class="">
        {% for action_type in action_types %}
            <div class="panel panel-default col-md-6">
                <div class="panel-body">
                    <a class="btn btn-success col-md-12" href="{% url 'bh:action_type' pk=action_type.pk %}">
                        {{ action_type.name }}
                    </a>
                </div>
            </div>
        {% endfor %}
        <div class="panel panel-default col-md-6">
            <div class="panel-body">
                <a class="btn btn-success col-md-12" href="{% url 'bh:action_type' pk=0 %}">
                    Без типа
                </a>
            </div>
        </div>
    </div>
{% endblock %}

bh/templates/bh/address.html
{% extends "bh/main.html" %}

{% block address %}active{% endblock %}

{% block content %}

    <h4>{{ address }}</h4>
	{% if address.people.count %}
        По этому адресу проживают:
        <ul>
            {% for person in address.people.all %}
                <li><a href="{% url 'bh:person' pk=person.pk %}">{{ person }}</a></li>
            {% endfor %}
        </ul>
	{% endif %}

    {% if address.lat and address.lng %}
        {% include 'bh/map.html' with address=address addreses=addresses %}
    {% endif %}

{% endblock %}

bh/templates/bh/address_list.html
{% extends "bh/main.html" %}

{% block address %}active{% endblock %}

{% block content %}
    <h3>Адреса</h3>
    <div class="list-group">
    {% for address in addresses %}
        <a class="list-group-item" href="{% url 'bh:address' pk=address.pk %}">{{ address }}</a>
    {% endfor %}
    </div>

    {% include 'bh/map.html' with address=addresses|first addresses=addresses %}
{% endblock %}

bh/templates/bh/event_list.html
{% extends "bh/main.html" %}

{% block events %}active{% endblock %}

{% block content %}
    <h3>События категории "{{ title }}"</h3>
	<div class="list-group">
		{% for event in events.all %}
			<a class="list-group-item" href="{% url 'bh:event' pk=event.pk %}">
				{{ event.started_at }}: {{ event.name }}
			</a>
		{% endfor %}
	</div>
{% endblock %}

bh/templates/bh/eventtype_list.html
{% extends "bh/main.html" %}

{% block events %}active{% endblock %}

{% block content %}
    <h3>Типы событий</h3>
    <div class="">
        {% for event_type in event_types %}
            <div class="panel panel-default col-md-6">
                <div class="panel-body">
                    <a class="btn btn-success col-md-12" href="{% url 'bh:event_type' pk=event_type.pk %}">
                        {{ event_type.name }}
                    </a>
                </div>
            </div>
        {% endfor %}
        <div class="panel panel-default col-md-6">
            <div class="panel-body">
                <a class="btn btn-success col-md-12" href="{% url 'bh:event_type' pk=0 %}">
                    Без типа
                </a>
            </div>
        </div>
    </div>
{% endblock %}

bh/templates/bh/index.html
{% extends 'bh/main.html' %}

{% block content %}
    Используйте меню
{% endblock %}

bh/templates/bh/people.html
{% extends "bh/main.html" %}

{% block people %}active{% endblock %}

{% block content %}
    <h3>Люди</h3>

    <form action="" method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            {% load bootstrap %}
            {{ form|bootstrap }}
            <div><a href="{% url 'bh:birthdays' %}">Дни рождения</a></div>
        </div>
        <div class="form-group text-center">
            <input type="submit" value="Фильтровать" class="btn btn-success"/>
        </div>
    </form>

    {% for person in people %}
        <div class="col-lg-6 col-md-6 col-sm-12" style="padding: 10px;">

            <div class="panel panel-default">

                <div class="panel-heading">
                    <a href="{% url 'bh:person' pk=person.id %}">
                        {{ person }}
                    </a>
                </div>

                <div class="panel-body">

                    {% load staticfiles %}
                    <div class='pull-left' style="box-shadow: 0 0 10px #ccc; width: 80px; height: 80px; padding: 5px; background: url({% static 'bh/img/noavatar.png' %}); background-position: center; background-size: cover; margin-right: 10px;">
                        {% if person.image %}
                            <div style="background: url({{ person.image.url }}); background-position: center; background-size: cover; width: 70px; height: 70px;"></div>
                        {% endif %}
                    </div>

                    {% if person.status %}
                        <p>{{ person.get_status_display }}</p>
                    {% endif %}

                    {% if person.phone.count %}
                        <p>
                            {% for p in person.phone.all %}
                                <a href="tel:{{ p.number }}">{{ p.number }}</a>{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </p>
                    {% endif %}

                </div>

            </div>

        </div>
    {% endfor %}
{% endblock %}

bh/templates/bh/person.html
{% extends "bh/main.html" %}

{% block people %}active{% endblock %}

{% block content %}
    <div class="panel {% if person.gone_to_eternity %}panel-success{% elif person.gone_to_another_church %}panel-warning{% elif person.gone %}panel-danger{% else %}panel-default{% endif %}">
        <div class="panel-heading">
            <h4>
                {{ person }}
                {% if user.is_superuser %}
                    <a href="{% url 'admin:bh_person_change' person.pk %}">Edit</a>
                {% endif %}
                {% if person.gone_to_eternity %}
                    ({% if person.gender == 'm' %}Отошел{% else %}Отошла{% endif %}
                    в вечность)
                {% elif person.gone_to_another_church %}
                    ({% if person.gender == 'm' %}Перешел{% else %}Перешла{% endif %}
                    в другую церковь)
                {% elif person.gone %}
                    ({% if person.gender == 'm' %}Ушел{% else %}Ушла{% endif %}
                    из церкви)
                {% endif %}
            </h4>
        </div>
        <div class="panel-body">
            {% if person.image %}
            <div class="col-md-2">
                {% if person.image %}
                    <a href="{{ person.image.url }}" target="_blank">
                        <img class="img-thumbnail" src="{{ person.image.url }}" alt="" width="100">
                    </a>
                {% endif %}
            </div>
            {% endif %}
            <div {% if person.image %}class="col-md-10"{% endif %}>

                <h4>
                    {% if person.staff %}
                        Должность в церкви: {{ person.staff|lower }}.
                    {% endif %}
                    {% if person.member %}Член церкви.{% endif %}
                    {% if person.baptized %}
                        Крещен{% if person.gender == 'f' %}а{% endif %}{% if  person.baptized_at %} {{ person.baptized_at }}{% endif %}.
                    {% endif %}
                </h4>

                {% if person.birthday %}
                    <h4>День рождения: {{ person.birthday }} ({{ person.birthday|timesince }})</h4>
                {% endif %}

                {% if person.address %}
                    <h4>Место жительства:
                        <a href="{% url 'bh:address' pk=person.address.pk %}">{{ person.address }}</a>
                    </h4>
                {% endif %}

                {# Род занятий #}
                {% if person.occupation %}
                    <p>Род занятий: {{ person.occupation }}</p>
                {% endif %}

                {# Образование, специальность #}
                {% if person.specialty %}
                    <p>Образование, специальность: {{ person.specialty }}</p>
                {% endif %}

                {% if person.email.count or person.social.count or person.phone.count %}
                    Контакты:
                    <ul>
                        {% for e in person.email.all %}
                            <li>e-mail: <a href="mailto:{{ e.address }}">{{ e.address }}</a></li>
                        {% endfor %}
                        {% for s in person.social.all %}
                            <li>{{ s.get_name_display }}: <a href="{{ s.link }}">{{ s.link }}</a></li>
                        {% endfor %}
                        {% for s in person.phone.all %}
                            <li>{{ s.get_type_display }}: {{ s.number }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}

                {% if person.relations.count %}
                    Семья:
                    <ul>
                        {% for r in person.relations.all %}
                            <li><a href="{% url 'bh:person' pk=r.rel.id %}">{{ r.get_type_display }}: {{ r.rel }}</a></li>
                        {% endfor %}
                    </ul>
                {% endif %}

                {% if person.skills.count %}
                    Навыки:
                    <ul>
                        {% for skill in person.skills.all %}
                            <li><a href="{% url 'bh:skill' pk=skill.pk %}">{{ skill }}</a></li>
                        {% endfor %}
                    </ul>
                {% endif %}

                {% if person.signed_documents.count %}
                    Подписанные документы:
                    <ul>
                        {% for document in person.signed_documents.all %}
                            <li>
                                {{ document }}
                                {% if document.event_types.count %}
                                    ({% for event_type in document.event_types.all %}{{ event_type }}{% endfor %})
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}

                {% if person.actions.count %}
                    Активности:
                    <ul>
                        {% for action_role in person.actions.all %}
                            <li>
                                <a href="{% url 'bh:action' pk=action_role.action.pk %}">
                                    {{ action_role.action.name }}
                                </a>
                                {% if action_role.role %}
                                    ({{ action_role.role|lower }})
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}

                {% if person.events.count %}
                    События:
                    <ul>
                        {% for event in person.events.all %}
                            <li>
                                <a href="{% url 'bh:event' pk=event.pk %}">
                                    {{ event.started_at }}: {{ event.name }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}

                {% if person.description %}
                    <h4>Примечания:</h4>
                    <p>{{ person.description }}</p>
                {% endif %}

            </div>

        </div>
    </div>

{% endblock %}

bh/templates/bh/skill.html
{% extends "bh/main.html" %}

{% block skills %}active{% endblock %}

{% block content %}
	<h3>{{ skill }}</h3>
	<div class="list-group">
		{% for person in skill.people.all %}
			<a class="list-group-item" href="{% url 'bh:person' pk=person.pk %}">{{ person }}</a>
		{% endfor %}
	</div>
{% endblock %}